version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    container_name: nginx
    restart: always
    volumes:
      - ./static/logo.svg:/html/static/logo.svg:ro
      - ./static/logo-white.svg:/html/static/logo-white.svg:ro
      - ./swifty.config.json:/html/swifty.config.json:ro
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    ports:
      - 80:80
      - 443:443

volumes:
    certs:
      external:
        name: certs
    certs-data:
      external:
        name: certs-data